#!/usr/bin/env python3

import sys

def print_help():
	print("HELP")

def error(msg):
	print(msg)
	exit(84)

def getConnectionsList():
	tab = []
	try:
		with open(sys.argv[1]) as file:
			for line in file:
				elem = line.replace("\n", "").replace(" is friends with ", "\\").split("\\")
				if len(elem) != 2:
					error("ERROR: Incorrect file content !")
				tab.append(elem)
		return tab
	except:
		error("ERROR: Could not use file !")

def getFriendsList(friends_list):
	tab = []
	for elem in friends_list:
		for name in elem:
			if name not in tab:
				tab.append(name)
	tab.sort()
	return tab

def main():
	case = 0
	if len(sys.argv) == 2 and sys.argv[1] == "-h":
		print_help()
		exit(0)
	if len(sys.argv) == 3:
		case = 1
	elif len(sys.argv) == 4:
		case = 2
	else:
		error("ERROR: Refer to -h for correct use")
	connections_list = getConnectionsList()
	friends_list = getFriendsList(connections_list)
	if case == 4:
		p1 = sys.argv[2]
		p2 = sys.argv[3]
	print(connections_list)
	print(friends_list)

if __name__ == '__main__':
	main()
