#!/usr/bin/env python3

from math import *
import sys
import time
import getpass

def printHelp():
   print("USAGE")
   print("\t./206neutrinos n a h sd");
   print("");
   print("DESCRIPTION");
   print("\tn\tnumber of values");
   print("\ta\tarithmetic mean");
   print("\th\tharmonic mean");
   print("\tsd\tstandard deviation");
   exit (0);

if __name__ == '__main__':
   if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
      printHelp()
   if(len(sys.argv) != 5):
      print("Prog is taking 4 arg -h for mor informations");
      exit (84);
   nb_value = int(sys.argv[1]);
   while (1):
      nb_value = nb_value + 1;
      mdpe = input("indtast din vaerdi :\t")
      if (mdpe == "ENDE"):
          exit (0);
      if (not (mdpe.isdigit())):
         exit (84);
      print("antal mãlinder :\t%d" %nb_value);
